# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Free Period Directory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Free Period Directory
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
